# Master_Sequence
bank_id         = [ 0x01, 0x00 ]
# Sample Medium types [ram/unk/cart/ddrive]
medium_type     = "cart"
# Sequence Player types [sfx/fanfare/bgm/demo]
sequence_player = "sfx"
# [ allow_enemy_bgm/fanfare/fanfare_ganon/restore/section_store/section_preserve/io7_1/no_ambience]
sequence_flags  = [ "fanfare" ]
